# Generated by Django 4.2.27 on 2026-02-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posp_code', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy_number', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='core.client')),
            ],
        ),
    ]
