# Generated by Django 4.2.27 on 2026-02-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_convertedpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posp_code', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy_number', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ConvertedPolicy',
        ),
        migrations.AddField(
            model_name='leadconversion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='core.client'),
        ),
    ]
