# Generated by Django 4.2.27 on 2026-02-06 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leadconversion_client_is_converted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadconversion',
            old_name='customer_number',
            new_name='customer_name',
        ),
    ]
