# Generated by Django 4.2.27 on 2026-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_customer_number_leadconversion_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsurance',
            name='age',
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='ages',
            field=models.TextField(default=[], help_text='JSON string: [25] or [30,28,5]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='floater_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('family', 'Family')], default=[], max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='ped',
            field=models.TextField(blank=True, help_text='Pre-existing disease details'),
        ),
    ]
