# Generated by Django 4.2.27 on 2026-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_healthinsurance_age_healthinsurance_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurance',
            name='ages',
            field=models.CharField(help_text='Comma separated ages', max_length=100),
        ),
    ]
