# Generated by Django 4.2.27 on 2026-02-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_healthinsurance_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurance',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='renewal_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
