# Generated by Django 4.2.27 on 2026-02-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_healthinsurance_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinsurance',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
