# Generated by Django 4.2.27 on 2026-03-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehicleinsurance_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurance',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='emi_tenure',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='monthly_emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='policy_tenure',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicleinsurance',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinsurance',
            name='emi_tenure',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicleinsurance',
            name='monthly_emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinsurance',
            name='policy_tenure',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
