# Generated by Django 4.2.27 on 2026-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_userapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('HOT', 'HOT'), ('WARM', 'WARM'), ('COOL', 'COOL')], default='HOT', max_length=10),
        ),
    ]
