# Generated by Django 4.2.27 on 2026-07-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_note_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insurance_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('health', 'Health'), ('investment', 'Investment')], max_length=10),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('sip', 'SIP'), ('mutual_fund', 'Mutual Fund'), ('fixed_deposit', 'Fixed Deposit'), ('ulip', 'ULIP'), ('nps', 'NPS'), ('bond', 'Bond'), ('other', 'Other')], max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('monthly_sip', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nominee_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_details', to='core.client')),
            ],
        ),
    ]
