# Generated by Django 4.2.27 on 2026-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_client_insurance_type_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='maturity_date',
            new_name='renewal_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='expected_returns',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='monthly_sip',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='nominee_name',
        ),
        migrations.AddField(
            model_name='leadconversion',
            name='investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='leadconversion',
            name='paying_term',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leadconversion',
            name='policy_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='policy_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
