# Generated by Django 4.2.27 on 2026-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_notes_investment_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadconversion',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='leadconversion',
            name='paying_term',
        ),
        migrations.RemoveField(
            model_name='leadconversion',
            name='policy_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='insurance_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('health', 'Health')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='customer_mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='policy_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leadconversion',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
