# Generated by Django 4.2.27 on 2026-07-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_leadconversion_investment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insurance_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('health', 'Health'), ('investment', 'Investment')], max_length=10),
        ),
        migrations.CreateModel(
            name='InvestmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_details', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posp_code', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('policy_name', models.CharField(max_length=200)),
                ('investment_paying_term', models.CharField(max_length=100)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_conversions', to='core.client')),
            ],
        ),
    ]
