# Generated by Django 4.2.27 on 2026-07-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_client_insurance_type_investmentdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_provider', models.CharField(blank=True, default='', max_length=200)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('policy_tenure', models.CharField(blank=True, default='', max_length=100)),
                ('emi_tenure', models.CharField(blank=True, default='', max_length=100)),
                ('monthly_emi_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_details', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
