# Generated by Django 4.2.27 on 2026-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_emidetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emidetails',
            name='emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
