# Generated by Django 4.2.27 on 2026-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_emidetails_emi_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insurance_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('health', 'Health'), ('investment', 'Investment')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='healthinsurance',
            name='renewal_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentdetails',
            name='renewal_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='renewal_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['follow_up_date', 'reminder', 'completed'], name='core_note_follow__f288b5_idx'),
        ),
    ]
